
/*
 * Copyright 2020, Data61, CSIRO (ABN 41 687 119 230)
 ** SPDX-License-Identifier: BSD-2-Clause
 */

/* This header was generated by kernel/tools/invocation_header_gen.py.
 *
 * To add an invocation call number, edit libsel4/include/interfaces/sel4.xml.
 *
 */
#ifndef __LIBSEL4_ARCH_INVOCATION_H
#define __LIBSEL4_ARCH_INVOCATION_H
enum arch_invocation_label {
    ARMPageTableMap = nSeL4ArchInvocationLabels,
    ARMPageTableUnmap,
#if defined(CONFIG_TK1_SMMU)
    ARMIOPageTableMap,
#endif
#if defined(CONFIG_TK1_SMMU)
    ARMIOPageTableUnmap,
#endif
    ARMPageMap,
    ARMPageUnmap,
#if defined(CONFIG_TK1_SMMU)
    ARMPageMapIO,
#endif
    ARMPageClean_Data,
    ARMPageInvalidate_Data,
    ARMPageCleanInvalidate_Data,
    ARMPageUnify_Instruction,
    ARMPageGetAddress,
    ARMASIDControlMakePool,
    ARMASIDPoolAssign,
#if defined(CONFIG_ARM_HYPERVISOR_SUPPORT)
    ARMVCPUSetTCB,
#endif
#if defined(CONFIG_ARM_HYPERVISOR_SUPPORT)
    ARMVCPUInjectIRQ,
#endif
#if defined(CONFIG_ARM_HYPERVISOR_SUPPORT)
    ARMVCPUReadReg,
#endif
#if defined(CONFIG_ARM_HYPERVISOR_SUPPORT)
    ARMVCPUWriteReg,
#endif
#if defined(CONFIG_ARM_HYPERVISOR_SUPPORT)
    ARMVCPUAckVPPI,
#endif
    ARMIRQIssueIRQHandlerTrigger,
#if CONFIG_MAX_NUM_NODES > 1
    ARMIRQIssueIRQHandlerTriggerCore,
#endif
#if defined(CONFIG_ARM_SMMU)
    ARMSIDIssueSIDManager,
#endif
#if defined(CONFIG_ARM_SMMU)
    ARMSIDGetFault,
#endif
#if defined(CONFIG_ARM_SMMU)
    ARMSIDClearFault,
#endif
#if defined(CONFIG_ARM_SMMU)
    ARMSIDBindCB,
#endif
#if defined(CONFIG_ARM_SMMU)
    ARMSIDUnbindCB,
#endif
#if defined(CONFIG_ARM_SMMU)
    ARMCBIssueCBManager,
#endif
#if defined(CONFIG_ARM_SMMU)
    ARMCBTLBInvalidateAll,
#endif
#if defined(CONFIG_ARM_SMMU)
    ARMCBAssignVspace,
#endif
#if defined(CONFIG_ARM_SMMU)
    ARMCBUnassignVspace,
#endif
#if defined(CONFIG_ARM_SMMU)
    ARMCBTLBInvalidate,
#endif
#if defined(CONFIG_ARM_SMMU)
    ARMCBGetFault,
#endif
#if defined(CONFIG_ARM_SMMU)
    ARMCBClearFault,
#endif
    nArchInvocationLabels
};

#endif /* __LIBSEL4_ARCH_INVOCATION_H */
